config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carrental.urls')),
    path('dashboard/', include('dashboard.urls')),
]

carrental/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.templatetags.static import static
from django.contrib.auth.models import User
# Create your models here.


class CarBrends(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name


class CarModels(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    carbrends = models.ForeignKey(CarBrends, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class CarYear(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name


class CarPrice(models.Model):
    price_1 = models.CharField(max_length=20, null=True, blank=True)
    price_2 = models.CharField(max_length=20, null=True, blank=True)
    price_3 = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return f"{self.price_1}, {self.price_2}, {self.price_3}"


class Cars(models.Model):
    is_konditsioner = models.BooleanField()
    is_gps = models.BooleanField()
    is_bagaj = models.BooleanField()
    is_musiqa = models.BooleanField()
    is_kamar = models.BooleanField()
    is_audio_kiritsh = models.BooleanField()
    is_bluethooth = models.BooleanField()
    is_uzoq_masofa = models.BooleanField()
    is_uxlash_stoli = models.BooleanField()
    is_kalit_plut = models.BooleanField()
    is_bortli_kompyuter = models.BooleanField()

    image = models.ImageField(upload_to="static/car/image", null=True, blank=True)
    kilometers = models.IntegerField(null=True, blank=True)
    mator = models.CharField(max_length=50, null=True, blank=True)
    sat_down = models.IntegerField(null=True, blank=True)
    baggage = models.CharField(max_length=50, null=True, blank=True)
    fuel = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    carmodels = models.ForeignKey(CarModels, related_name="carmodels", on_delete=models.SET_NULL, null=True, blank=True)
    caryear = models.ForeignKey(CarYear, related_name="caryear", on_delete=models.SET_NULL, null=True, blank=True)
    carprices = models.ForeignKey(CarPrice, related_name="carprices", on_delete=models.SET_NULL, null=True, blank=True)
    update = models.DateTimeField(auto_now=True)
    carprice = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.carmodels.name)

    @property
    def get_image(self):
        return self.image.url if self.image else static('')

    def save(self, *args, **kwargs):
        # Ushbu misolda allaqachon fayl borligini tekshiring
        try:
            this = Cars.objects.get(id=self.id)
            # Agar fayl mavjud bo'lsa va yangi fayl bilan bir xil bo'lmasa, eski faylni o'chiring
            if this.image and this.image != self.image:
                this.image.delete(save=False)
        except Cars.DoesNotExist:
            pass

        super(Cars, self).save(*args, **kwargs)


class CarRentai(models.Model):
    user = models.ForeignKey(User, related_name="user_profile", on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    images = models.ImageField(upload_to="static/users/img", null=True, blank=True)
    pasport = models.ImageField(upload_to="static/users/pasport", null=True, blank=True)
    prava = models.ImageField(upload_to="static/users/prava", null=True, blank=True)
    phone = models.CharField(max_length=13, null=True, blank=True, unique=True)
    def __str__(self):
        return str(self.user)

    @property
    def get_image_user(self):
        return self.images.url if self.images else static('admins/default-profile-picture.png')
    
    @property
    def get_image_pasport(self):
        return self.pasport.url if self.pasport else static('')
    
    @property
    def get_image_prava(self):
        return self.prava.url if self.prava else static('')


class Manzil1(models.Model):
    manzil1 = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.manzil1}"

class Manzil2(models.Model):
    manzil2 = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.manzil2}"

class Booking(models.Model):
    manzil1 = models.ForeignKey(Manzil1, on_delete=models.SET_NULL, null=True, blank=True)
    manzil2 = models.ForeignKey(Manzil2, on_delete=models.SET_NULL, null=True, blank=True)
    sana1 = models.DateField()
    sana2 = models.DateField()
    vaqt = models.CharField(max_length=7, null=True, blank=True)

    def __str__(self):
        return f"{self.manzil1}"

class Review(models.Model):
    is_comentary = models.BooleanField(null=True, default=False)
    STATUS_CHOICES = (
        ('yangi', 'Yangi'),
        ('berildi', 'Berildi'),
        ('qaytarildi', 'Qaytarildi'),
        ('rad etildi', 'Rad etildi'),
    )
    carrentai = models.ForeignKey(CarRentai, related_name="carrentai", on_delete=models.CASCADE, null=True, blank=True)
    cars = models.ForeignKey(Cars, related_name="cars", on_delete=models.SET_NULL, null=True, blank=True)
    booking = models.ForeignKey(Booking, related_name="booking", on_delete=models.SET_NULL, null=True, blank=True)
    review = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(1), MaxValueValidator(5)])
    description = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='yangi', null=True)
    update = models.DateTimeField(auto_now=True)
    createdate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.cars.carmodels.name)

templates/admins/mashina/car_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Mashina qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="image">Mashina:</label>
                                            {{forms.image}}
                                            <!-- <input type="file" name="image" id="image" class="form-control"> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="kilometers">Bosib o'tgan yo'l:</label>
                                            {{forms.kilometers}}
                                            <!-- <input type="number" id="kilometers" name="kilometers" class="form-control" value="{{forms.kilometers}}"> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="mator">mator:</label>
                                            {{forms.mator}}
                                            <!-- <input type="text" id="mator" name="mator" class="form-control" placeholder="" value="{{forms.mator}}"> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="sat_down">O'rindiqlar soni:</label>
                                            {{forms.sat_down}}
                                            <!-- <input type="number" id="sat_down" name="sat_down" class="form-control"> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="baggage">Bagaj sig'imi:</label>
                                            {{forms.baggage}}
                                            <!-- <input type="text" id="baggage" name="baggage" class="form-control" placeholder=""> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="fuel">Yoqilg'i:</label>
                                            {{forms.fuel}}
                                            <!-- <input type="text" id="fuel" name="fuel" class="form-control" placeholder=""> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="description">Manshinaga izoh:</label>
                                            {{forms.description}}
                                            <!-- <textarea name="description" id="description" class="form-control"></textarea> -->
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label>Mashina turi: <a href="{% url 'carmodels_input' %}">+</a></label>
                                            {{forms.carmodels}}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label>caryear: <a href="{% url 'caryear_input' %}">+</a></label>
                                            {{forms.caryear}}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label>carprices: <a href="{% url 'carprice_input' %}">+</a></label>
                                            {{forms.carprices}}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_konditsioner" class="form-check-label">
                                                {{forms.is_konditsioner}}
                                                is_konditsioner
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_gps" class="form-check-label">
                                                {{forms.is_gps}}
                                                is_gps
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div><div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_bagaj" class="form-check-label">
                                                {{forms.is_bagaj}}
                                                is_bagaj
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div><div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_musiqa" class="form-check-label">
                                                {{forms.is_musiqa}}
                                                is_musiqa
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_kamar" class="form-check-label">
                                                {{forms.is_kamar}}
                                                is_kamar
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_audio_kiritsh" class="form-check-label">
                                                {{forms.is_audio_kiritsh}}
                                                is_audio_kiritsh
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_bluethooth" class="form-check-label">
                                                {{forms.is_bluethooth}}
                                                is_bluethooth
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_uzoq_masofa" class="form-check-label">
                                                {{forms.is_uzoq_masofa}}
                                                is_uzoq_masofa
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_uxlash_stoli" class="form-check-label">
                                                {{forms.is_uxlash_stoli}}
                                                is_uxlash_stoli
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_kalit_plut" class="form-check-label">
                                                {{forms.is_kalit_plut}}
                                                is_kalit_plut
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_bortli_kompyuter" class="form-check-label">
                                                {{forms.is_bortli_kompyuter}}
                                                is_bortli_kompyuter
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}

templates/admins/mashina/carbreand_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Mashina brendi qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="image">Mashina brendi:</label>
                                            {{forms.name}}
                                            <!-- <input type="file" name="image" id="image" class="form-control" required> -->
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}

templates/admins/mashina/carmodels_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Mashina modeli qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">Mashina nomi:</label>
                                            {{forms.name}}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="carbrends">Mashina brendi:<a href="{% url 'carbreand_input' %}">+</a></label>
                                            {{forms.carbrends}}
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}

templates/admins/mashina/carprice_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Mashina yili qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">1 kunlin summa:</label>
                                            {{forms.price_1}}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">1 haftalik summa:</label>
                                            {{forms.price_2}}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">1  oylik summa:</label>
                                            {{forms.price_3}}
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}

templates/admins/mashina/caryear_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Mashina yili qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">Mashina yili:</label>
                                            {{forms.name}}
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}

templates/admins/mashina/manzil_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Manzil qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">Mashinani olib ketish manzili:</label>
                                            {{forms.manzil1}}
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label for="name">Mashinani tashlab ketish manzili:</label>
                                            {{form.manzil2}}
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}