config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carrental.urls')),
    path('dashboard/', include('dashboard.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext
from django.templatetags.static import static


def admin_directory_path(instance, filename):
    # File will be uploaded to MEDIA_ROOT/user_<id>/avatar/<filename>
    return f'user_{instance.user.id}/avatar/{filename}'


class AdminProfile(models.Model):
    is_self_visible = models.BooleanField(default=False, null=True, blank=True)
    is_admin = models.BooleanField(default=False, null=True, blank=True)
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_CHOICES = [
        (GENDER_MALE, gettext("Erkak")),
        (GENDER_FEMALE, gettext("Ayol")),
    ]
    user = models.OneToOneField(User, related_name="admin_profile", on_delete=models.CASCADE)
    admin_avatar = models.ImageField(upload_to="static/admin/profiles/", null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=32, null=True, blank=True)
    gender = models.PositiveSmallIntegerField(choices=GENDER_CHOICES, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: 
        verbose_name = gettext('Profile')
        verbose_name_plural = gettext('Profiles')

    @property
    def get_admin_avatar(self):
        return self.admin_avatar.url if self.admin_avatar else static('admins/default-profile-picture.png')
 
    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Ushbu misolda allaqachon fayl borligini tekshiring
        try:
            this = AdminProfile.objects.get(id=self.id)
            # Agar fayl mavjud bo'lsa va yangi fayl bilan bir xil bo'lmasa, eski faylni o'chiring
            if this.admin_avatar and this.admin_avatar != self.admin_avatar:
                this.admin_avatar.delete(save=False)
        except AdminProfile.DoesNotExist:
            pass

        super(AdminProfile, self).save(*args, **kwargs)

templates/admins/admin/admins.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}

<style>
    @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro);

body {
  background: #ffffff;
  color: #414141;
  font: 400 17px/2em 'Source Sans Pro', sans-serif;
}

.select-box {
  cursor: pointer;
  position : relative;
  max-width:  20em;
  margin: 5em auto;
  width: 100%;
}

.select,
.label {
  color: #414141;
  display: block;
  font: 400 17px/2em 'Source Sans Pro', sans-serif;
}

.select {
  width: 100%;
  position: absolute;
  top: 0;
  padding: 5px 0;
  height: 40px;
  opacity: 0;
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
  background: none transparent;
  border: 0 none;
}
.select-box1 {
  background: #ececec;
}

.label {
  position: relative;
  padding: 5px 10px;
  cursor: pointer;
}
.open .label::after {
   content: "▲";
}
.label::after {
  content: "▼";
  font-size: 12px;
  position: absolute;
  right: 0;
  top: 0;
  padding: 5px 15px;
  border-left: 5px solid #fff;
}
</style>

<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-6 d-flex justify-content-start">
                                    <h4 class="card-title">Kitoblar royxati</h4>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Qidirish...">
                                        <div class="input-group-append">
                                            <button type="button" class="btn btn-secondary btn-icon-text">
                                                <i class="typcn typcn-zoom-in-outline icon-md"></i>
                                                Qidirish
                                            </button>
                                        </div>
                                    </div>&nbsp;&nbsp;
                                    <a href="{% url 'admins_input' %}" class="btn  btn-success"> Qo'shish</a>
                                </div>
                            </div><br>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th>
                                            Rasm
                                        </th>
                                        <th>
                                           Username
                                        </th>
                                        <th>
                                           Ism familiya
                                        </th>
                                        <th>
                                            Huquqlar
                                        </th>
                                        <th>
                                            Yaralgan vaqt
                                        </th>
                                        <th>
                                            Harakat
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for profile in profiles %}
                                    <tr>
                                        <td class="py-3">
                                            <img src="{{profile.get_admin_avatar}}" alt="image"/>
                                        </td>
                                        <td>
                                            {{profile.user.username}}
                                        </td>
                                        <td>
                                            {{profile.user.first_name}} {{profile.user.last_name}}
                                        </td>
                                        <td>
                                            {% if profile.is_admin %}
                                            Super admin
                                            {% elif profile.is_admin_senior %}
                                            Katta admin
                                            {% elif profile.is_admin_junior %}
                                            Kichik admin
                                            {% elif profile.is_admin_middle %}
                                            O'rta admin
                                            {% else %}
                                            Admin emas
                                            {% endif %}
                                        </td>
                                        <td>
                                            {{profile.created_at}}
                                        </td>
                                        <td>
                                            <a href="{% url 'admins_edit' pk=profile.id %}"
                                               class="btn btn-outline-secondary btn-rounded ">
                                                <i class="typcn typcn-edit text-succes "></i>
                                            </a>
                                            <a href=""
                                               class="btn btn-outline-secondary btn-rounded ">
                                                <i class="typcn typcn-archive text-danger"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->

</div>

<script src="">
    $("select").on("click" , function() {

$(this).parent(".select-box").toggleClass("open");

});

$(document).mouseup(function (e)
{
var container = $(".select-box");

if (container.has(e.target).length === 0)
{
    container.removeClass("open");
}
});


$("select").on("change" , function() {

var selection = $(this).find("option:selected").text(),
  labelFor = $(this).attr("id"),
  label = $("[for='" + labelFor + "']");

label.find(".label-desc").html(selection);

});
</script>
{% endblock content %}

templates/admins/admin/admins_input.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Admin qo'shish</h4>
                            <p class="card-description">
                            </p>
                            <form class="forms-sample" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            <label>Username: <a href="{% url 'create_admin' %}">+</a></label>
                                            {{forms.user}}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_admin" class="form-check-label">
                                                {{forms.is_admin}}
                                                Admin
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-check form-check-info">
                                            <label for="id_is_self_visible" class="form-check-label">
                                                {{forms.is_self_visible}}
                                                Katta admin
                                                <i class="input-helper"></i></label>
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                                <a href="#" class="btn btn-light">Ortga qaytish</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>
<script>
    document.getElementById('fileInput').addEventListener('change', function() {
        var fileName = this.value.split('\\').pop();
        var fileUploadInfo = document.querySelector('.file-upload-info');
        if (fileName) {
            fileUploadInfo.value = fileName;
        } else {
            fileUploadInfo.value = "Fayl yuklash";
        }
    });
</script>

{% endblock content %}

templates/admins/admin/create_admin.html
{% extends "admins/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid page-body-wrapper">
    {% include 'admins/sidbare.html' %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-md-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Admin</h4>
                            <p class="card-description">
                                Admin qo'shish
                            </p>
                            <form class="forms-sample" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="username">Username</label>
                                            {{ forms.username }}
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email manzil</label>
                                            {{ forms.email }}
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label for="id_password1">Parol</label>
                                            <input class="form-control" type="password" name="password1" autocomplete="new-password" required="" id="id_password1">
                                        </div>
                                        <div class="form-group">
                                            <label for="id_password2">Parol 2</label>
                                            <input class="form-control" type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-secondary mr-2">Register</button>
                                <button type="button" class="btn btn-light">Cancel</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        {% include 'admins/footer.html' %}
    </div>
    <!-- main-panel ends -->


</div>

{% endblock content %}


<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Register</title>-->
<!--</head>-->
<!--<body>-->
<!--<h1>Register</h1>-->
<!--&lt;!&ndash;<form method="post">&ndash;&gt;-->
<!--&lt;!&ndash;    {% csrf_token %}&ndash;&gt;-->
<!--&lt;!&ndash;    {{ forms.as_p }}&ndash;&gt;-->
<!--&lt;!&ndash;    <button type="submit">Register</button>&ndash;&gt;-->
<!--&lt;!&ndash;</form>&ndash;&gt;-->
<!--</body>-->
<!--</html>-->

templates/admins/admin/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TATU Samarqand filiali</title>
  <link rel="stylesheet" href="{% static 'admins/vendors/typicons.font/font/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'admins/vendors/css/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'admins/css/vertical-layout-light/style.css' %}">
  <link rel="shortcut icon" href="{% static 'admins/images/favicon.png' %}" />

</head>

<body>
  {% include 'admins/natification.html' %}
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-5 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo text-center">
                <img src="{% static 'admins/images/icon.png' %}" alt="logo" style="height: 80px; width: 80px;" >
              </div>
              <h3 class="text-center">Toshkent axborot texnologiyalari universiteti</h3>
              <h5 class="font-weight-light text-center">Samarqand filiali</h5>
              <form method="post"  class="mt-4" id="loginForm"
              onsubmit="return validateForm()">
                {% csrf_token %}
                <div class="form-group">
                  <label for="exampleInputUsername">Username</label>
                  <input type="text" class="form-control form-control-lg" id="exampleInputUsername" name="username" placeholder="Foydalanuvchi nomi">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Parol</label>
                  <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" name="password" placeholder="Parol">
                </div>
                <div class="my-2 d-flex justify-content-between align-items-center">
                  <a href=""  class="auth-link text-black">Parolni unutdingizmi?</a>
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn btn-block btn-facebook auth-form-btn" onclick="validateForm()" id="btn">
                       Tizimga kirish
                    </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'admins/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'admins/js/off-canvas.js' %}"></script>
  <script src="{% static 'admins/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'admins/js/template.js' %}"></script>
  <script src="{% static 'admins/js/settings.js' %}"></script>
  <script src="{% static 'admins/js/todolist.js' %}"></script>

</body>

</html>

templates/admins/admin/profile.html
{% extends "admins/base.html" %}
{% load static %}
{% block content %}
    <div class="container-fluid page-body-wrapper">
        {% include 'admins/sidbare.html' %}
        <div class="main-panel">
          <div class="content-wrapper">
            <form action="{% url 'admin_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
            <div class="row">
                <div class="col-md-8 grid-margin stretch-card">
                        <div class="card mb-3" style="max-width: 540px;">
                            <div class="row g-0">
                                <div class="col-md-12">
                                    <div class="card-body">
                                        <h1 class="text-center">Mening profilim</h1>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="card-body">
                                        <img src="{{ admin_profile.get_admin_avatar }}" class="img-fluid rounded-start" alt="rasm" style="border-radius: 8%;">
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="card-body">
                                        <p class="text h3">{{ admin_profile.user.get_full_name }}</p>
                                        <p class="text">{{ admin_profile.user.username }}</p>
                                        <p class="text">{{ request.user.email }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>      
                </div>
                <div class="col-md-8 grid-margin stretch-card">
                        <div class="card">
                        <div class="card-body">
                            <!-- <h4 class="card-title">Shavkat Jo'raboyev</h4>
                            <p class="card-description">
                            Shaxsiy ma'lumotlar
                            </p> -->
                            <div class="form-group row">
                                <label for="first_name" class="col-sm-3 col-form-label">Ism</label>
                                <div class="col-sm-9">
                                <input type="text" name="first_name" value="{{ admin_profile.user.first_name }}" class="form-control form-control-lg border-success"  placeholder="Ism">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Familiya</label>
                                <div class="col-sm-9">
                                <input type="text" name="last_name" value="{{ admin_profile.user.last_name }}" class="form-control form-control-lg border-success"  placeholder="Familiya">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputEmail" class="col-sm-3 col-form-label">Email</label>
                                <div class="col-sm-9">
                                <input type="email" name="email" class="form-control form-control-lg border-success" id="exampleInputEmail" placeholder="info@gmail.com" value="{{ admin_profile.user.email }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputMobile" class="col-sm-3 col-form-label">Telefon</label>
                                <div class="col-sm-9">
                                <input type="number" name="phone" class="form-control form-control-lg border-success" id="exampleInputMobile" placeholder="+998901234567" value="{{ admin_profile.phone }}">
                                </div>
                            </div>
                        </div>
                        </div>
                </div>
                <div class="col-md-8 grid-margin stretch-card">
                        <div class="card">
                        <div class="card-body">
                            
                            <div class="form-group row">
                                <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Tug'ilgan yil</label>
                                <div class="col-sm-9">
                                    <input type="text" name="birthday" class="form-control form-control-lg border-success" placeholder="yyyy-mm-dd" aria-label="birthday" pattern="\d{4}-\d{2}-\d{2}" value="{{ admin_profile.birthday|date:'Y-m-d' }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Jins</label>
                                <div class="col-sm-9">
                                    <select name="gender" class="form-control form-control-lg border-success" id="gender"
                                    aria-label="Gender select example">
                                        <option>Jins</option>
                                        {% for key, value in admin_profile.GENDER_CHOICES %}
                                        <option value="{{ key }}"
                                            {% if admin_profile.gender == key %} selected {% endif %}>{{ value }}
                                        </option>
                                {% endfor %}
                                      </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputMobile" class="col-sm-3 col-form-label">Profil rasm</label>
                                <div class="col-sm-9">
                                <input type="file" name="admin_avatar" class="form-control form-control-lg border-success" id="exampleInputMobile" placeholder="rasm">
                                </div>
                            </div>
                            <!-- <div class="form-group">
                                <label for="username" class="col-sm-3 col-form-label">Parolni o'zgartirish:</label>
                                <a href="" class="btn btn-secondary">O'zgartirish</a>
                            </div> -->
                            <button type="submit" class="btn btn-secondary mr-2">Saqlash</button>
                            <a href="" class="btn btn-light">Bekor qilish</a>
                        </div>
                        </div>
                </div>
            </div>
        </form>
          </div>
          <!-- content-wrapper ends -->
          {% include 'admins/footer.html' %}
        </div>
        <!-- main-panel ends -->
       
       
    </div>
   
{% endblock content %}